name: pylops_mpi
channels:
  - defaults
  - conda-forge
dependencies:
  - python >= 3.8.0
  - pip
  - numpy>=1.21.0
  - scipy>=1.8.0
  - mpi4py
  - pylops >= 2.0
  - matplotlib
  - ipython
  - pytest
  - pytest-mpi
  - pytest-runner
  - setuptools_scm
  - Sphinx
  - numpydoc
  - numba
  - nbsphinx
  - pydata-sphinx-theme
  - flake8
  - pip:
      - sphinx-gallery
